Cloudflow first project
Danstnou/cloudflowPayments pull request #3
Opened 2020-09-22 15:55 UTC by Danstnou

поправил процессор, убрал лишнее и добавил проект Postman. Но ещё в работе

2020-09-22 16:03 UTC, MaxSbk requested changes
Давай почистим репозиторий от ненужного хлама. **.idea**, **target** директории относятся к этому.

2020-09-22 16:04 UTC, Danstnou commented
окей!

2020-09-22 16:07 UTC, MaxSbk commented
> окей!
Так же предлагаю немного исправить .gitignore:

`# Eclipse
.classpath
.project
.settings/

# Intellij
.idea/
*.iml
*.iws

# Maven
log/
target/

# App
out/
/.toDelete
`

2020-09-22 16:10 UTC, MaxSbk requested changes

2020-09-22 16:10 UTC, MaxSbk commented on datamodel/src/main/avro/logMessage.avsc
> +         }
Попрошу в схемах avro добавить для каждого поля doc с описанием что за поле и для чего.

2020-09-22 16:25 UTC, MaxSbk requested changes

2020-09-22 16:25 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +  class EnrichmentFunction extends RichCoFlatMapFunction[Participant, Payment, LogMessage] {
Не нужно такое в одном файле держать, раскидай по scala файлам

2020-09-22 16:25 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +//case class LogMessage(reason: String, message: String, level: String)
Комментарии убираем

2020-09-22 16:32 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +  class EnrichmentFunction extends RichCoFlatMapFunction[Participant, Payment, LogMessage] {
*FlatMapFunction наверное тут излишен, можно обойтись CoProcessFunction

2020-09-22 18:16 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +  class EnrichmentFunction extends RichCoFlatMapFunction[Participant, Payment, LogMessage] {
исправил и закоммитил.
после исправлений, нужно здесь (в текущем pull request) сообщать об этом?

2020-09-22 18:36 UTC, MaxSbk requested changes

2020-09-22 18:36 UTC, MaxSbk commented on checking/src/main/scala/payments.checking/PaymentCheckingStreamlet.scala
> +      writeStream(invalid, stream.getSideOutput(loggerTag))
Тут необязательно оба типа в SideOutput пихать. Лучше сделать через MapFunction, где invalid например засунуть в SideOutput, а valid будут передаваться в том же потоке stream. И функцию в отдельный класс

2020-09-22 18:36 UTC, MaxSbk commented on ingestor/src/main/scala/payments/ingestor/FilePaymentsIngress.scala
> +          FileIO.fromPath(_).via(Framing.delimiter(ByteString("\r\n"), 128, allowTruncation = true))
Магические числа вида "\r\n" и 128 выносим либо в конфиги, либо в поля класса/компаньёна

2020-09-22 18:36 UTC, MaxSbk commented on logger/src/main/scala/payments/logger/PaymentLoggingEgress.scala
> +  var inProcessor = AvroInlet[LogMessage]("in-processor")
Почему var? Исправь везде где нет необходимости в изменяемых переменных

2020-09-22 18:36 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +  class EnrichmentFunction extends RichCoFlatMapFunction[Participant, Payment, LogMessage] {
Просто отписывай в reply к моим сообщениям

2020-09-23 06:44 UTC, Danstnou commented on checking/src/main/scala/payments.checking/PaymentCheckingStreamlet.scala
> +      writeStream(invalid, stream.getSideOutput(loggerTag))
В sideOutput вынес только логирование(оставив основным Transfer => Payment), но правда не получилось через MapFunction, потому что нет доступа к Context, через который можно записать запись в sideOutput.
Магические числа вынес в компаньон, а сообщения при логировании в конфиг.
Я гадаю, нужно ли выносить отдельно ключи ConfigParameter и названия StreamletPort'ов?

2020-09-23 09:20 UTC, MaxSbk commented on checking/src/main/scala/payments.checking/PaymentCheckingStreamlet.scala
> +      writeStream(invalid, stream.getSideOutput(loggerTag))
Понял, можно тогда вот это применять: https://ci.apache.org/projects/flink/flink-docs-release-1.9/api/java/org/apache/flink/streaming/api/functions/ProcessFunction.html

2020-09-23 09:21 UTC, MaxSbk commented on checking/src/main/scala/payments.checking/PaymentCheckingStreamlet.scala
> +      writeStream(invalid, stream.getSideOutput(loggerTag))
По каждому замечанию отписывай пожалуйста ответы в отдельные reply-и

2020-09-23 09:43 UTC, Danstnou commented on checking/src/main/scala/payments.checking/PaymentCheckingStreamlet.scala
> +      writeStream(invalid, stream.getSideOutput(loggerTag))
ProcessFunction так и осталась, просто теперь в sideOutput записываю только invalid.
а валидные (сформированные Payment) передаются в этом же потоке (т.е. это выход стрима)

2020-09-23 09:43 UTC, Danstnou commented on ingestor/src/main/scala/payments/ingestor/FilePaymentsIngress.scala
> +          FileIO.fromPath(_).via(Framing.delimiter(ByteString("\r\n"), 128, allowTruncation = true))
Магические числа вынес в компаньон, а сообщения при логировании в конфиг.
Не уверен, нужно ли выносить отдельно ключи ConfigParameter и названия StreamletPort'ов?

2020-09-23 09:43 UTC, Danstnou commented on logger/src/main/scala/payments/logger/PaymentLoggingEgress.scala
> +  var inProcessor = AvroInlet[LogMessage]("in-processor")
исправил

2020-09-23 10:40 UTC, MaxSbk commented on checking/src/main/scala/payments.checking/PaymentCheckingStreamlet.scala
> +      writeStream(invalid, stream.getSideOutput(loggerTag))
Прошу прощения, все смешалось в один коммент, поэтому и прошу отвечать в каждом за свои, в идеале ещё и коммиты по одному на замечание

2020-09-23 10:49 UTC, MaxSbk requested changes

2020-09-23 10:49 UTC, MaxSbk commented on logger/src/main/scala/payments/logger/PaymentLoggingEgress.scala
> +  val inProcessor           = AvroInlet[LogMessage]("in-processor")
Можно попробовать убрать второй вход, оставив один, в который передавать из двух разных стримлетов. в blueprint-е по идее будет два продюсера в один консюмер у топика. Попробуй

2020-09-23 10:49 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingFunction.scala
> +      val withdrawnBalance = fromParticipant.balance - value
Стоит ли сначала вычитать, а потом проверять результат, или лучше сначала проверить, возможен ли перевод, а потом уже его делать?

2020-09-23 10:49 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Попробуй привязаться к схеме путём указания конкретного поля для keyBy, а не имени поля. _.myBank

2020-09-23 10:50 UTC, MaxSbk commented on ingestor/src/main/scala/payments/ingestor/FilePaymentsIngress.scala
> +          FileIO.fromPath(_).via(Framing.delimiter(ByteString("\r\n"), 128, allowTruncation = true))
Нет, такое не выносим

2020-09-23 11:13 UTC, Danstnou commented on logger/src/main/scala/payments/logger/PaymentLoggingEgress.scala
> +  val inProcessor           = AvroInlet[LogMessage]("in-processor")
в логере убрал 2-ой вход, оставил 1: 
```
val in  = AvroInlet[LogMessage]("in")
```
в blueprint'e оба продюсера передают в этот 1 "in"
```
checking-logger {
      producers = [checking.out-logger]
      consumers = [logger.in]
}
processor-logger {
      producers = [processor.out]
      consumers = [logger.in]
}
```
но:
[error] 'logger.in' is bound to more than one topic: checking-logger,processor-logger.
ошибка, что вход привязан к более, чем одной теме

2020-09-23 11:17 UTC, MaxSbk commented on logger/src/main/scala/payments/logger/PaymentLoggingEgress.scala
> +  val inProcessor           = AvroInlet[LogMessage]("in-processor")
нет, я предлагал попробовать что то вроде:
logging {
      producers = [checking.out-logger, processor.out]
      consumers = [logger.in]
}

2020-09-23 11:38 UTC, Danstnou commented on logger/src/main/scala/payments/logger/PaymentLoggingEgress.scala
> +  val inProcessor           = AvroInlet[LogMessage]("in-processor")
аа, понял, у меня было 2 разных топика для логера. а теперь логер читает из одного топика(logging), в который складывают 2 продюсера. исправил

2020-09-23 12:08 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingFunction.scala
> +      val withdrawnBalance = fromParticipant.balance - value
исправил проверкой наличия достаточного баланса:
```if (fromParticipant.balance >= value)```

2020-09-23 12:25 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
а это не название поля, а функции (input => key), которые возвращают константу "myBank", просто для одного ключа для их общего состояния

2020-09-23 12:34 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Ты привязываешься к наименованию поля, которое в переменной. Если изменится схема, компиляция пройдёт, но уже в рантайме отвалится. Это плохо

2020-09-23 12:37 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Формируй ключ из сообщения

2020-09-23 12:43 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
UPD_2: Кстати, для keyedStream-ов используют KeyedCoProcessFunction

2020-09-23 12:47 UTC, MaxSbk requested changes

2020-09-23 12:47 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingFunction.scala
> +case class LogMessage(reason: String, message: String, level: String)
Мне казалось ты убрал эти классы? Почему то в стримлете PaymentProcessingStreamlet в типах Inlet-ов и outlet-ов на них ссылаются, а не на сгенерированные в Авро классы. Проверь плз

2020-09-23 12:50 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
да один ключ, константа "myBank". 
Просто получается в схеме **Participant(id, balance)** и **Payment(from, to, value)**, должно быть какое-нибудь общее поле, по которому я могу объединить их для общего состоянии. Мне добавить поле, например "idBank"?

2020-09-23 12:51 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingFunction.scala
> +case class LogMessage(reason: String, message: String, level: String)
да, извини, я просто так добавляю, чтобы красным не подсвечивалось) в след. коммите уберу, и добавлять не буду

2020-09-23 13:09 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
idBank скорее всего не подходит, потому что тогда может возникнуть ситуация что в to будет тот, кого не окажется под нужным ключем, а нам платежи нужно передавать между разными банками.

2020-09-23 13:12 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Можно ввести искусственное поле для разделения всех возможных платежей и балансов. Например CountryCode. Тогда в рамках одной страны возможен будет перевод только клиенту этой же страны. По бизнесу уже более подходит.

2020-09-23 13:13 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
А вот обработать ситуацию когда тот кто переводит и тот кому приходит перевод в разных странах, можно будет реализовать в следующей итерации, если останется время

2020-09-23 13:16 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Кажется есть так же возможность реализовать функционал используя BroadcastProcessFunction

2020-09-23 13:18 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingFunction.scala
> +case class LogMessage(reason: String, message: String, level: String)
avro схемы же компилируются в классы и помещаются в classpath проекта, по идее красным не должно подсвечиваться

2020-09-23 13:33 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
окей!
просто не до конца понятен смысл, я думал всё в рамках одного банка, и поэтому добавил искусственную константу "myBank".
если например сделать CountryCode, перевод будет в рамках одной страны, а баланс клиента в состоянии будет относиться к какому банку?
и то есть перевод должен быть в рамках не одного банка?
если так, то как узнать из маски **клиент1 => клиент2 : 100** без указания банка, в каком именно банке клиенту2 переводится, а то так можно Broadcast нескольким банкам
немного запутался(

2020-09-23 13:37 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Ну сейчас банков вообще нет

2020-09-23 13:46 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
окей, тогда через BroadcastProcessFunction буду делать!

2020-09-23 13:50 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Вообще Идеи по модификации глубоко поддерживаются, если что, если если вводятся bankId, то ограничение переводов только по банку мне кажется сильно не нужным. И придётся что то придумывать для обхода этого. BroadCast же просто распараллелит стейт на все имеющиеся операторы, что даст нужный эффект

2020-09-23 13:55 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
окей!

2020-09-24 05:29 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Хотел спросить насчёт BroadcastProcessFunction. Я думал сделать поток платежей - non-broadcasted, а поток участников с балансом - broadcasted.
Но судя из документации, из processElement где я обрабатывал бы платежи, ReadOnlyContext не предоставляет возможности изменить состояние broadcast state в котором и хранились бы участники с балансом.
Продолжать работу с Broadcast, или пересмотреть подход?

2020-09-24 07:03 UTC, MaxSbk commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Да уж, засада. Для текущей задачи не подходит кажется. Т.е. измнения в стейте не зафиксируются по факту. В общем есть идея, чтобы не тянуть время, ввести поля валюты, и ключевать потоки по валюте. Т.е. валюта будет в балансе каждого юзера + валюта будет в каждом переводе(не забыть про регулярку и строки перевода). Единственно что, стейт изменится. Попробуй

2020-09-24 07:11 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
понял, спасибо!

2020-09-24 11:33 UTC, Danstnou commented on processor/src/main/scala/payments/processor/PaymentProcessingStreamlet.scala
> +          .keyBy(_ => idBank, _ => idBank)
Добавил. Правда, наверное теперь, можно хранить в стейте не полностью MapState[String, Participant], а что-то наподобие MapState[String, Account(balance)] id/баланс?

2020-09-25 15:43 UTC, MaxSbk commented
LGTM

2020-09-25 15:44 UTC, merged